// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearSelections(): $CancellablePromise<$models.RosterData> {
    return $Call.ByID(2518837069);
}

export function ExportExcel(selections: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3740649158, selections);
}

export function ExportImage(base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3543154816, base64Data);
}

export function GenerateDraft(): $CancellablePromise<$models.RosterData> {
    return $Call.ByID(4240835961);
}

export function GetConfig(): $CancellablePromise<$models.ConfigData> {
    return $Call.ByID(1200034045);
}

export function GetRosterData(): $CancellablePromise<$models.RosterData> {
    return $Call.ByID(1276498460);
}

export function LoadFile(): $CancellablePromise<$models.RosterData> {
    return $Call.ByID(56829399);
}

export function LoadState(): $CancellablePromise<$models.RosterData> {
    return $Call.ByID(3556934338);
}

export function SaveState(selections: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(2941707333, selections);
}
