// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CategoryConfigItem {
    "roles": string[] | null;
    "color": string;
    "textCol": string;
}

export interface ConfigData {
    "rolesOrder": string[] | null;
    "bandRoles": string[] | null;
    "cleanupOptions": string[] | null;
    "categoryConfig": { [_ in string]?: CategoryConfigItem } | null;
    "themes": { [_ in string]?: Theme } | null;
    "roleToCat": { [_ in string]?: RoleCat } | null;
}

export interface MemberInfo {
    "roles": string[] | null;
    "availString": string;
}

export interface RoleCat {
    "cat": string;
    "color": string;
}

export interface RosterData {
    "weekColumns": string[] | null;
    "allMembers": { [_ in string]?: MemberInfo } | null;
    "availabilityMap": { [_ in string]?: { [_ in string]?: string[] | null } | null } | null;
    "initialRoster": { [_ in string]?: { [_ in string]?: string } | null } | null;
    "config": ConfigData;
}

export interface Theme {
    "bgMain": string;
    "bgSec": string;
    "fgPri": string;
    "fgSec": string;
    "inputBg": string;
    "inputBorder": string;
    "inputSel": string;
    "dashBgWarn": string;
    "dashBgNotice": string;
    "dashTextAvail": string;
    "dashTextUnavail": string;
    "activeCellText": string;
    "cats": { [_ in string]?: string } | null;
}
