// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelections() {
  return window['go']['main']['App']['ClearSelections']();
}

export function ExportExcel(arg1) {
  return window['go']['main']['App']['ExportExcel'](arg1);
}

export function ExportImage(arg1) {
  return window['go']['main']['App']['ExportImage'](arg1);
}

export function GenerateDraft() {
  return window['go']['main']['App']['GenerateDraft']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRosterData() {
  return window['go']['main']['App']['GetRosterData']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}
