// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSelections():Promise<main.RosterData>;

export function ExportExcel(arg1:Record<string, string>):Promise<void>;

export function ExportImage(arg1:string):Promise<void>;

export function GenerateDraft():Promise<main.RosterData>;

export function GetConfig():Promise<main.ConfigData>;

export function GetRosterData():Promise<main.RosterData>;

export function LoadFile():Promise<main.RosterData>;

export function LoadState():Promise<main.RosterData>;

export function SaveState(arg1:Record<string, string>):Promise<void>;
